name: Main

on: [pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci --legacy-peer-deps
      - name: run eslint
        run: npm run lint
      - name: run tests
        run: npm run test
